from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 24)
        self.cell(0, 10, 'Sahil Gaikwad', align='C', new_x="LMARGIN", new_y="NEXT")
        self.set_font('helvetica', '', 12)
        self.cell(0, 8, 'Wakad, Pune | 9168073559 | sahilgaikwad2002official@gmail.com', align='C', new_x="LMARGIN", new_y="NEXT")
        self.line(10, 30, 200, 30)
        self.ln(5)

pdf = PDF()
pdf.add_page()
pdf.set_font('helvetica', 'B', 16)
pdf.cell(0, 10, 'Objective', new_x="LMARGIN", new_y="NEXT")
pdf.line(10, pdf.get_y(), 200, pdf.get_y())
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(0, 6, 'Computer Engineering graduate with a strong foundation in Java Full-Stack Development and 1.4 years of professional experience in operations. Proven ability to build scalable Java applications and manage complex data systems. Seeking to leverage technical expertise in Core Java, SQL, and JSP/Servlets to contribute to WNS engineering team.')
pdf.ln(5)

pdf.set_font('helvetica', 'B', 16)
pdf.cell(0, 10, 'Professional Experience', new_x="LMARGIN", new_y="NEXT")
pdf.line(10, pdf.get_y(), 200, pdf.get_y())
pdf.set_font('helvetica', 'B', 12)
pdf.cell(100, 8, 'WNS Global Services', align='L')
pdf.cell(0, 8, '27/09/2024 - 02/02/2026', align='R', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('helvetica', 'I', 11)
pdf.cell(0, 6, 'Associate In Operations', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(0, 6, '- Managed billing processes using IBM i (AS/400) systems.\n- Maintained high accuracy in data operations and documentation.\n- Collaborated with global teams to ensure timely delivery of service goals.')
pdf.ln(5)

pdf.set_font('helvetica', 'B', 16)
pdf.cell(0, 10, 'Education', new_x="LMARGIN", new_y="NEXT")
pdf.line(10, pdf.get_y(), 200, pdf.get_y())
pdf.set_font('helvetica', 'B', 12)
pdf.cell(100, 8, 'Savitribai Phule Pune University', align='L')
pdf.cell(0, 8, '2021-2024', align='R', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('helvetica', '', 11)
pdf.cell(0, 6, 'B.E. Computer Engineering - 72.20%', new_x="LMARGIN", new_y="NEXT")
pdf.ln(2)
pdf.set_font('helvetica', 'B', 12)
pdf.cell(100, 8, "Met's Institute Of Polytechnic Nashik", align='L')
pdf.cell(0, 8, '2018-2021', align='R', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('helvetica', '', 11)
pdf.cell(0, 6, 'Diploma In Computer Engineering - 85.71%', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)

pdf.set_font('helvetica', 'B', 16)
pdf.cell(0, 10, 'Skills', new_x="LMARGIN", new_y="NEXT")
pdf.line(10, pdf.get_y(), 200, pdf.get_y())
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(0, 6, '- Languages: Java (Core & Advanced), SQL, HTML5, CSS3.\n- Java Technologies: JSP, Servlets, JDBC, Java Collections Framework, OOP Concepts.\n- Database: MySQL, Oracle.\n- Tools & Platforms: Git/GitHub, Maven, Eclipse, IntelliJ IDEA, IBM i (AS/400).\n- Concepts: Data Structures & Algorithms (DSA), Database Management Systems (DBMS).')
pdf.ln(5)

pdf.set_font('helvetica', 'B', 16)
pdf.cell(0, 10, 'Projects', new_x="LMARGIN", new_y="NEXT")
pdf.line(10, pdf.get_y(), 200, pdf.get_y())
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, 'Student Management System (Java Full-Stack)', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(0, 6, '- Role: Full-Stack Developer\n- Tech Stack: Java, Servlets, JSP, JDBC, MySQL.\n- Key Contribution: Developed a complete web application to manage student records with full CRUD functionality. Implemented session management and secure database connectivity using JDBC.')
pdf.ln(2)

pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, 'Smart Bank Transaction System (Java & Collections)', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(0, 6, '- Role: Backend Developer\n- Tech Stack: Java Collections (ArrayList, HashMap).\n- Key Contribution: Built transaction logic to handle deposits and withdrawals. Leveraged HashMaps for O(1) time complexity in account retrieval and implemented custom Exception Handling.')

pdf.output("Sahil_Gaikwad_Resume.pdf")
